# Add configuration values here, as shown below.
#
pusher_app_id: "735558"
pusher_key: 2a0e191a544c745780f0
pusher_secret: 7fa58d449883d3e9c3bc
puhser_cluster: "ap2"

# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
